### ISSUE TITLE
Allow html interface to open shortcuts/programs/other features

### ISSUE THREAD

**Issue by naeem76** [rocksdanister/lively#198]
**Is your feature request related to a problem? Please describe.**
Not a problem, but rather a feature, I was hoping we could use the internal cef webview to interact with .NET, the inspiration came from creating a good UI in html, and allowing buttons to open some shortcuts

**Describe the solution you'd like**
JS interop with CEF Webview for each feature, eg opening shortcuts/programs, with lively properties to save user choice

**Describe alternatives you've considered**
Currently just thought of shortcuts

**Additional context**
I will implement it myself, if you think the feature is worth having

**Comment by rocksdanister** [comment]
Is this not a Security risk?  allowing webpages to execute programs/commands on host machine.

**Comment by naeem76** [comment]
Ideally not any program, and obviously not set up by the webpage itself, lively user will choose ProgramA.exe on shortcutA, web will invoke 'shortcutA'. 
We can add a global setting to enable this feature, disabled by default.

**Comment by rocksdanister** [comment]
>Ideally not any program

So a curated list of programs allowed by Lively?

>lively user will choose ProgramA.exe on shortcutA, web will invoke 'shortcutA'.

By user do you mean end user or wallpaper maker? ie is this selection a UI shown by lively or is it a configuration file written by the wallpaper maker.

**Comment by naeem76** [comment]
Wallpaper maker ONLY has access to lively shortcut1, shortcut2 etc. lets call it launcher api from lively.

I guess it will be a configuration file written by the wallpaper maker, maybe a new lively property type in the json? and then the end user will select what programs to connect with each property.

**Comment by rocksdanister** [comment]
So like in Lively customize menu users can browse and link actions for shortcuts made by wallpaper maker? 🤔
Actions need to be stored in a separate file.

**Comment by naeem76** [comment]
I guess its still a bit confusing for you, I think if I show you some changes its better, can I add you on discord? I am having some trouble with dev environment

**Comment by naeem76** [comment]
@rocksdanister I am sorry I didn't mean to offend you with discord e.e

Anyways I made some draft PRs with prototypes, if you think its okay or not
#200 
https://github.com/rocksdanister/lively-cef/pull/18

**Comment by rocksdanister** [comment]
> I am having some trouble with dev environment

I wrote some instructions on the wiki:
https://github.com/rocksdanister/lively/wiki/Building

>I am sorry I didn't mean to offend you with discord e.e

Not sure what you mean.

I am taking a break from looking at the issues for few days.. feeling a bit burned out. 
(also can't even compile lively in my system now.. tried installing visual studio preview for WinUI preview 3 and my whole dev tools are messed up.)

I'll have a look later 👍

**Comment by naeem76** [comment]
Ah I'm sorry, Burn out is a real issue, take a break for a few days!

I fixed the dev environment, no worries

**Comment by rocksdanister** [comment]
So I had a look at the code (didn't run it because my dev setup is still broken.)
Looks like the shortcut is added through Lively UI? I don't agree with this.
To me this is more appropriate to be added in LivelyProperty itself rather than integrating it into the main UI.

Here is my idea:
1. A custom LivelyProperty control `applauncher`
2. Wallpaper maker can only add the control, not specify the path to the file. (LivelyProperty.info will only contain the name of the applauncher control.)
3. Wallpaper maker will have to add `--app-launcher` argument to `LivelyInfo.json` inorder to let Lively know this feature is required.
4. When lively knows this feature is requested, Lively will auto generate the `LivelyLauncher.json` file during wallpaper initialization in `WebProcess.cs` contructor.
5. Users will see an empty app launcher control like this when clicked Customise wallpaper:
![Screenshot 2020-11-21 184400](https://user-images.githubusercontent.com/17554161/99878209-c24c6580-2c29-11eb-91ce-378992e7a10d.jpg)
6. When you select a application Lively updates the LivelyLauncher.json file and sends message to livelycefsharp program to reload the file.
7. Launching the program will be handled by livelycefsharp program ( or Lively can do it, just need to pass a message from livelycefsharp to lively saying shortcut1 requested etc.)
8. (Optional) Some pre defined shortcuts for some basic apps/system menu.
9. A sort of timeout should be implemented, so that user won't accidently spam launch.
10. A setting to turn off this feature/warning to user maybe in Lively UI.
11. (TODO) Demo wallpaper - something like a ps4 menu to launch programs and shortcuts.

**Comment by naeem76** [comment]
You are absolutely correct, it wont be in main lively ui for final version, it was just to show the prototype for how the app launcher will work sort of.

I think all your points are fine, I will start working on it.

For point no 7 currently it is launched by the livelyCEF, if thats fine i will stick to it.

For point 11, you mean something to showcase the new feature right? I already have something in the works

**Comment by rocksdanister** [comment]
>For point no 7 currently it is launched by the livelyCEF, if thats fine i will stick to it.

Yeah that's fine.

>For point 11, you mean something to showcase the new feature right? I already have something in the works

Yes, would be nice. If its small enough I can bundle it with lively; on somewhat related note are you familiar with any ipc system like gRPC?

**Comment by rocksdanister** [comment]
@naeem76 Hope you are doing fine.
Since there has been no more message exchange I'm assuming something came up and you are no longer developing the launcher?

**Comment by naeem76** [comment]
@rocksdanister ah I'm sorry, yes something came up and I had to put it on hold, and then completely forgot. Let me know if I should continue this, or help with something else. Also for gRPC, no I don't have direct experience with it.

**Comment by rocksdanister** [comment]
No worries.

> Let me know if I should continue this, or help with something else. 

If interested you can proceed with this, I just asked to determine whether I should take up this issue or not.

>Also for gRPC, no I don't have direct experience with it.

Wanted to try using gRPC to make the core and ui separate program, had some doubts that's why I asked.

**Comment by Abhid14** [comment]
So sir my use case is the client himself/herself adds a list of programs and shortcuts in a folder and lists them using a json file. Next they register on their wish the link to the shortcuts manually using admin rights to the registry. Now the client can use that custom protocol links to open that shortcut from any browser or lively. Just an explicit method or api would be very helpful to open that link. also as the html and javascript file can be inspected by anyone to see and edit its behavior when they use it as everything is open sourced.
More info
https://docs.microsoft.com/en-us/windows/win32/search/-search-3x-wds-ph-install-registration
